VOTE-445 Add Yup'ik translation to vote.gov
usagov/vote-gov pull request #602
Opened 2022-08-19 23:31 UTC by rayestrada

2022-08-23 15:15 UTC, mlloydbixal submitted a review, later dismissed

2022-08-29 21:00 UTC, SamiraMSadat requested changes
Mandy, there a few minor revisions to complete before approving the review. Thanks!

2022-08-30 18:38 UTC, mlloydbixal approved these changes

2022-08-30 19:57 UTC, SamiraMSadat approved these changes
Looks good!

2022-08-30 21:42 UTC, merged