VOTE-1197: add translation strings and generate markdown files
usagov/vote-gov pull request #828
Opened 2023-04-20 20:12 UTC by mlloydbixal

2023-05-10 23:29 UTC, rayestrada requested changes
Before I continue review can you make sure that "In English" is showing up for links that are not translated like the other translations?

2023-05-10 23:29 UTC, rayestrada commented on config/_default/languages.json
> +      "english_languageName": "Hatian Creole"
typo

2023-05-12 00:05 UTC, rayestrada requested changes

2023-05-12 00:05 UTC, rayestrada commented on data/translations/ht/homepage.json
> +  "registered__resources_link_text": "resous sou vote ak eleksyon",
Add (in english) translation to link text

2023-05-12 17:59 UTC, mlloydbixal commented on content/ht/konsènan-nou.html
> +meta_description = "Vote.gov is a United States government website that provides trusted voting information and can help you find voter registration rules for your state."
I think we are still waiting on translations for the About Us meta data and the 4th accordion

2023-05-12 18:17 UTC, mlloydbixal commented on content/ht/konsènan-nou.html
> +meta_description = "Vote.gov is a United States government website that provides trusted voting information and can help you find voter registration rules for your state."
Found it!

2023-05-12 23:06 UTC, rayestrada approved these changes

2023-05-17 23:43 UTC, rayestrada requested changes

2023-05-17 23:43 UTC, rayestrada commented on content/ht/about-us.html
> +<p>Jodi a, ekip Vote.gov kontinye amelyore sit entènèt la pou atenn objektif ki tabli nan <a href="https://www.whitehouse.gov/briefing-room/presidential-actions/2021/03/07/executive-order-on-promotin
Missing last sentence in last paragraph.
```
Objektif sa yo enkli amelyore kapasite pou jwenn aksè, tradui zouti votè yo nan lang kle yo, epi amelyore fonksyonalite rechèch sou sitwèb la.
```

2023-05-17 23:43 UTC, rayestrada commented on data/translations/ht/state-data.json
> +        "default_ip_deadline": "Disponib jiska jou Eleksyon an",
This change needs to be done for all `default_ip_deadline`

2023-05-19 23:36 UTC, rayestrada submitted a review, later dismissed

2023-05-24 18:49 UTC, rayestrada approved these changes

2023-05-24 18:50 UTC, merged

2023-05-26 15:05 UTC, rayestrada commented
Resolves #816