VOTE-1199 Add global configs and JSON content for Russian language
usagov/vote-gov pull request #834
Opened 2023-04-26 18:50 UTC by SamiraMSadat

https://bixal-projects.atlassian.net/browse/VOTE-1199

2023-05-06 00:11 UTC, rayestrada requested changes

2023-05-06 00:11 UTC, rayestrada commented on data/translations/ru/state-data.json
> +    "default_mail_received_deadline": "Должен быть получен за 13 дней до дня выборов",
Spot checking this is the wrong number of days. Can you recheck this whole document against the english version of the site to make sure there is no regressions to the number of days.

2023-05-06 00:11 UTC, rayestrada commented on data/translations/ru/register.json
> +  "alert_state__alert_after_election": "Для получения официальных результатов выборов перейдите по ссылке (веб-сайта вашего штата)",
Replace:
`"alert_state__alert_after_election": "Для получения официальных результатов выборов перейдите по ссылке %link%",`

2023-05-06 00:11 UTC, rayestrada commented on data/translations/ru/register.json
> +  "confirm_registration__url": "https://sos.wyo.gov/Elections/Docs/WYCountyClerks.pdf?ref=voteusa_en"
These properties have the wrong keys
```
  "confirm_registration__intro_WY": "Вы можете подтвердить свой статус регистрации избирателя, связавшись с местным регистрационным офисом. %link%.",
  "confirm_registration__link_WY": "Нажмите здесь, чтобы просмотреть контактную информацию клерка округа Вайоминг (PDF)",
```
Delete the property: `confirm_registration__url`

2023-05-10 23:46 UTC, rayestrada approved these changes

2023-05-17 21:42 UTC, mlloydbixal submitted a review, later dismissed

2023-05-19 23:27 UTC, rayestrada approved these changes

2023-05-24 18:37 UTC, rayestrada approved these changes

2023-05-24 18:38 UTC, merged