Vote-1194: Arabic translation
usagov/vote-gov pull request #838
Opened 2023-05-02 20:28 UTC by mlloydbixal

2023-05-09 00:16 UTC, rayestrada requested changes

2023-05-09 00:16 UTC, rayestrada commented on data/translations/ar/state-data.json
> +    "default_ip_deadline": "30 يومًا قبل يوم الانتخابات"
Missing "default_mail_postmarked_deadline"

2023-05-09 00:16 UTC, rayestrada commented on data/translations/ar/state-data.json
> +    "mail_received_deadline": "يجب أن يتم الاستلام قبل 15 يومًا من يوم الانتخابات"
this should be "default_mail_received_deadline"

2023-05-09 00:16 UTC, rayestrada commented on data/translations/ar/state-data.json
> +    "mail_received_deadline": "يجب أن يتم الاستلام قبل 15 يومًا من يوم الانتخابات"
fix key name "default_mail_received_deadline"

2023-05-09 00:16 UTC, rayestrada commented on data/translations/ar/state-data.json
> +    "default_ip_deadline": "60 يومًا قبل يوم الانتخابات"
missing "default_mail_received_deadline"

2023-05-09 00:16 UTC, rayestrada commented on data/translations/ar/state-data.json
> +    "mail_received_deadline": "يجب أن يتم الاستلام قبل 10 أيام من يوم الانتخابات"
fix key "default_mail_received_deadline"

2023-05-09 00:16 UTC, rayestrada commented on data/translations/ar/state-data.json
> +    "mail_received_deadline": "يجب الختم بختم البريد قبل 21 يومًا من يوم الانتخابات",
fix key "default_mail_received_deadline"

2023-05-09 00:16 UTC, rayestrada commented on data/translations/ar/state-data.json
> +    "mail_received_deadline": "يجب أن يتم الاستلام قبل 13 يومًا من يوم الانتخابات"
fix key "default_mail_received_deadline"

2023-05-09 00:16 UTC, rayestrada commented on data/translations/ar/state-data.json
> +    "mail_received_deadline": "يجب أن يتم الاستلام قبل 21 يومًا من يوم الانتخابات"
fix key "default_mail_received_deadline"

2023-05-09 00:16 UTC, rayestrada commented on data/translations/ar/state-data.json
> +    "mail_received_deadline": "يجب أن يتم الاستلام قبل 21 يومًا من يوم الانتخابات"
fix key "default_mail_received_deadline"

2023-05-09 00:16 UTC, rayestrada commented on data/translations/ar/state-data.json
> +    "mail_received_deadline": "يجب الاستلام قبل 11 يومًا عمل من يوم الانتخابات",
fix key "default_mail_received_deadline"

2023-05-09 00:16 UTC, rayestrada commented on data/translations/ar/state-data.json
> +    "mail_received_deadline": "يجب أن يتم الاستلام قبل 21 يومًا من يوم الانتخابات",
fix key "default_mail_received_deadline"

2023-05-09 00:16 UTC, rayestrada commented on data/translations/ar/state-data.json
> +    "mail_received_deadline": "يجب أن يتم الاستلام قبل 29 يومًا من يوم الانتخابات"
fix key "default_mail_received_deadline"

2023-05-12 00:11 UTC, rayestrada commented on data/translations/ar/state-data.json
> +    "default_ip_deadline": "30 يومًا قبل يوم الانتخابات"
No longer required.

2023-05-12 13:27 UTC, mlloydbixal commented on data/translations/ar/error.json
> +  "error_msg1": "إذا كتبت عنوان URL للصفحة، فإذا قمت بكتابة عنوان URL للصفحة ، فتحقق من الإملاء.",
I double checked the translation document and this is what they gave us.. perhaps they are saying "if you typed the page URL check the spelling of the URL" but I ran it through google translate and it sounds duplicated to me. However, I can't make sense of how to remove the duplication. I'll ask Omer to check with the translator.

2023-05-12 14:08 UTC, mlloydbixal commented on data/translations/ar/homepage.json
> +  "registered__resources_link_on": " %USA.gov% على",
I'm also removing it for Hindi

2023-05-12 23:24 UTC, rayestrada submitted a review, later dismissed

2023-05-22 18:24 UTC, rayestrada submitted a review, later dismissed

2023-06-12 21:53 UTC, rayestrada approved these changes

2023-06-12 21:53 UTC, merged