VOTE-714: Update Arizona registration link
usagov/vote-gov pull request #966
Opened 2024-01-18 15:17 UTC by SamiraMSadat

Jira: https://cm-jira.usa.gov/browse/VOTE-714

2024-01-19 18:18 UTC, clmedders submitted a review, later dismissed

2024-01-19 18:19 UTC, clmedders commented
@SamiraMSadat check this commit.. https://github.com/usagov/vote-gov/pull/966/commits/6907752d326b2da93ed49244e7b0bc1158bd29a8

There was an override link that needed to be updated.  if you are good with it im approving you can send over to Ray

2024-01-23 16:28 UTC, rayestrada requested changes

2024-01-23 16:28 UTC, rayestrada commented on data/translations/es/state-data.json
> +    "more_info_link_override": "https://azsos.gov/elections/voters/registering-vote/registerupdate-vote"
We don't need this override if it is not a translated link. It will use the default. Let's remove it.

2024-01-24 17:51 UTC, rayestrada approved these changes

2024-01-24 17:51 UTC, merged